### Do not change ###
- Region: ap-northeast-1
  InstanceSettings:
  - Name: g6-vcpu192-gpu8
    InstanceType: g6.48xlarge
    NunberOfCores: 192
    CostPerHours: 19.36206
  - Name: g6-vcpu96-gpu4
    InstanceType: g6.24xlarge
    NunberOfCores: 96
    CostPerHours: 9.68103
  - Name: g6-vcpu48-gpu4
    InstanceType: g6.12xlarge
    NunberOfCores: 48
    CostPerHours: 6.67369
  - Name: g6-vcpu64-gpu1
    InstanceType: g6.16xlarge
    NunberOfCores: 64
    CostPerHours: 4.92637
  - Name: g6-vcpu32-gpu1
    InstanceType: g6.8xlarge
    NunberOfCores: 32
    CostPerHours: 2.92148
  - Name: g6-vcpu16-gpu1
    InstanceType: g6.4xlarge
    NunberOfCores: 16
    CostPerHours: 1.91903
  - Name: g6-vcpu8-gpu1
    InstanceType: g6.2xlarge
    NunberOfCores: 8
    CostPerHours: 1.41781
  - Name: g6-vcpu4-gpu1
    InstanceType: g6.xlarge
    NunberOfCores: 4
    CostPerHours: 1.1672
  - Name: g5-vcpu192-gpu8
    InstanceType: g5.48xlarge
    NunberOfCores: 192
    CostPerHours: 23.62246
  - Name: g5-vcpu96-gpu4
    InstanceType: g5.24xlarge
    NunberOfCores: 96
    CostPerHours: 11.81123
  - Name: g5-vcpu48-gpu4
    InstanceType: g5.12xlarge
    NunberOfCores: 48
    CostPerHours: 8.22609
  - Name: g5-vcpu16-gpu1
    InstanceType: g5.4xlarge
    NunberOfCores: 16
    CostPerHours: 2.35528
  - Name: g4dn-vcpu96-gpu8
    InstanceType: g4dn.metal
    NunberOfCores: 96
    CostPerHours: 10.562
  - Name: g4dn-vcpu48-gpu4
    InstanceType: g4dn.12xlarge
    NunberOfCores: 48
    CostPerHours: 5.281
  - Name: c6i-vcpu128-gpu0
    InstanceType: c6i.32xlarge
    NunberOfCores: 128
    CostPerHours: 6.848
- Region: us-east-1
  InstanceSettings:
  - Name: g6-vcpu192-gpu8
    InstanceType: g6.48xlarge
    NunberOfCores: 192
    CostPerHours: 13.3504
  - Name: g6-vcpu96-gpu4
    InstanceType: g6.24xlarge
    NunberOfCores: 96
    CostPerHours: 6.6752
  - Name: g6-vcpu48-gpu4
    InstanceType: g6.12xlarge
    NunberOfCores: 48
    CostPerHours: 4.6016
  - Name: g6-vcpu64-gpu1
    InstanceType: g6.16xlarge
    NunberOfCores: 64
    CostPerHours: 3.3968
  - Name: g6-vcpu32-gpu1
    InstanceType: g6.8xlarge
    NunberOfCores: 32
    CostPerHours: 2.0144
  - Name: g6-vcpu16-gpu1
    InstanceType: g6.4xlarge
    NunberOfCores: 16
    CostPerHours: 1.3232
  - Name: g6-vcpu8-gpu1
    InstanceType: g6.2xlarge
    NunberOfCores: 8
    CostPerHours: 0.9776
  - Name: g6-vcpu4-gpu1
    InstanceType: g6.xlarge
    NunberOfCores: 4
    CostPerHours: 0.8048
  - Name: g5-vcpu192-gpu8
    InstanceType: g5.48xlarge
    NunberOfCores: 192
    CostPerHours: 16.288
  - Name: g5-vcpu96-gpu4
    InstanceType: g5.24xlarge
    NunberOfCores: 96
    CostPerHours: 8.144
  - Name: g5-vcpu48-gpu4
    InstanceType: g5.12xlarge
    NunberOfCores: 48
    CostPerHours: 5.672
  - Name: g5-vcpu16-gpu1
    InstanceType: g5.4xlarge
    NunberOfCores: 16
    CostPerHours: 1.624
  - Name: g4dn-vcpu96-gpu8
    InstanceType: g4dn.metal
    NunberOfCores: 96
    CostPerHours: 7.824
  - Name: g4dn-vcpu48-gpu4
    InstanceType: g4dn.12xlarge
    NunberOfCores: 48
    CostPerHours: 3.912
  - Name: c6i-vcpu128-gpu0
    InstanceType: c6i.32xlarge
    NunberOfCores: 128
    CostPerHours: 5.440
  - Name: m6i-vcpu128-gpu0
    InstanceType: m6i.32xlarge
    NunberOfCores: 128
    CostPerHours: 6.144
  - Name: r6i-vcpu128-gpu0
    InstanceType: r6i.32xlarge
    NunberOfCores: 128
    CostPerHours: 8.064
  - Name: c7i-vcpu192-gpu0
    InstanceType: c7i.48xlarge
    NunberOfCores: 192
    CostPerHours: 8.568
  - Name: m7i-vcpu192-gpu0 
    InstanceType: m7i.48xlarge
    NunberOfCores: 192
    CostPerHours: 9.6768
  - Name: r7i-vcpu192-gpu0
    InstanceType: r7i.48xlarge
    NunberOfCores: 192
    CostPerHours: 12.7008
# Spot Instance average of periods 2024/Feb/8 to 2024/Feb/15 at us-east-1c(use1-az4)
  - Name: g5-vcpu192-gpu8-spot
    InstanceType: g5.48xlarge-spot
    NunberOfCores: 192
    CostPerHours: 7.4722
  - Name: g5-vcpu96-gpu4-spot
    InstanceType: g5.24xlarge-spot
    NunberOfCores: 96
    CostPerHours: 4.0033
  - Name: g5-vcpu48-gpu4-spot
    InstanceType: g5.12xlarge-spot
    NunberOfCores: 48
    CostPerHours: 2.9119
  - Name: g4dn-vcpu96-gpu8-spot
    InstanceType: g4dn.metal-spot
    NunberOfCores: 96
    CostPerHours: 3.5863
  - Name: g4dn-vcpu48-gpu4-spot
    InstanceType: g4dn.12xlarge-spot
    NunberOfCores: 48
    CostPerHours: 1.6888
  - Name: c6i-vcpu128-gpu0-spot
    InstanceType: c6i.32xlarge-spot
    NunberOfCores: 128
    CostPerHours: 2.5405
  - Name: m6i-vcpu128-gpu0-spot
    InstanceType: m6i.32xlarge-spot
    NunberOfCores: 128
    CostPerHours: 2.8295
  - Name: r6i-vcpu128-gpu0-spot
    InstanceType: r6i.32xlarge-spot
    NunberOfCores: 128
    CostPerHours: 3.4519
  - Name: c7i-vcpu192-gpu0-spot
    InstanceType: c7i.48xlarge-spot
    NunberOfCores: 192
    CostPerHours: 3.9552
  - Name: m7i-vcpu192-gpu0-spot
    InstanceType: m7i.48xlarge-spot
    NunberOfCores: 192
    CostPerHours: 4.0849
  - Name: r7i-vcpu192-gpu0-spot
    InstanceType: r7i.48xlarge-spot
    NunberOfCores: 192
    CostPerHours: 7.0275
