### Do not Change ####
# item_tabale
MOTIONCOR2Executable: fn_motioncor2_exe
GctfExecutable: fn_gctf_exe
CTFFIND4Executable: fn_ctffind_exe
ResMapExecutable: fn_resmap
CrYOLOExecutable: fn_exe 
CrYOLORepo: param1_value
SelectClass3DExecutable: fn_exe
StackSplitExecutable: fn_exe
ResultMergeExecutable: fn_exe
BfactorPlotExecutable: fn_exe
