### Do not Change ####
# item_tabale
MOTIONCOR2Executable: fn_motioncor2_exe
CTFFIND4Executable: fn_ctffind_exe
GctfExecutable: fn_gctf_exe
CrYOLOExecutable: fn_exe 
CrYOLORepo: param1_value
SelectClass3DExecutable: fn_exe
ResMapExecutable: fn_resmap
BfactorPlotExecutable: fn_exe
