### Do not Change ####
- JobType: 'relion.class3d'
  JobOption:
  - Key: 'dont_skip_align'
    Value: 'Yes'
    AlgoTypeName: 'class3d_default'
  - Key: 'dont_skip_align'
    Value: 'No'
    AlgoTypeName: 'class3d_noalign'
- JobType: 'relion.class2d'
  JobOption:
  - Key: 'do_em'
    Value: 'Yes'
    AlgoTypeName: 'class2d_em'
  - Key: 'do_grad'
    Value: 'Yes'
    AlgoTypeName: 'class2d_vdam'
- JobType: 'relion.motioncorr'
  JobOption:
  - Key: 'do_own_motioncor'
    Value: 'Yes'
    AlgoTypeName: 'motioncorr_own'
  - Key: 'do_own_motioncor'
    Value: 'No'
    AlgoTypeName: 'motioncorr_mocor2'
- JobType: 'relion.ctffind'
  JobOption:
  - Key: 'use_gctf'
    Value: 'Yes'
    AlgoTypeName: 'ctffind_gctf'
  - Key: 'use_ctffind4'
    Value: 'Yes'
    AlgoTypeName: 'ctffind_ctff4'
- JobType: 'relion.external'
  JobOption:
  - Key: 'queuename'
    Value: 'cryolo'
    AlgoTypeName: 'external_cryolo'
  - Key: 'queuename'
    Value: 'select3d'
    AlgoTypeName: 'external_select3d'
- JobType: 'relion.select.onvalue'
  JobOption: 
  - Key: 'do_class_ranker'
    Value: 'Yes'
    AlgoTypeName: 'select_class2d'
  - Key: 'do_class_ranker'
    Value: 'No'
    AlgoTypeName: 'select'
- JobType: 'relion.select.split'
  JobOption:
  - Key: 'do_split'
    Value: 'Yes'
    AlgoTypeName: 'select_split'
  - Key: 'do_split'
    Value: 'No'
    AlgoTypeName: 'select'