### Do not Change ####
- JobType: 'relion.import.movies'
  JobOption:
  - Key: 'do_raw'
    Value: 'Yes'
    AlgoTypeName: 'import'
  - Key: 'do_raw'
    Value: 'No'
    AlgoTypeName: 'import'
- JobType: 'relion.import.other'
  JobOption:
  - Key: 'do_other'
    Value: 'Yes'
    AlgoTypeName: 'import'
  - Key: 'do_other'
    Value: 'No'
    AlgoTypeName: 'import'
- JobType: 'relion.motioncorr'
  JobOption:
  - Key: 'do_own_motioncor'
    Value: 'Yes'
    AlgoTypeName: 'motioncorr_own'
  - Key: 'do_own_motioncor'
    Value: 'No'
    AlgoTypeName: 'motioncorr_mocor2'
# NOTE: 2024/09/13 Toshio Moriya
# The following RELION Job parameters of relion.ctffind have been existed until relion/5.0-beta-0
# but both were removed from relion/5.0-beta-1
# The algorithm type of the first entry will be priotized if the parameter is not supported.
- JobType: 'relion.ctffind'
  JobOption:
  - Key: 'use_ctffind4'
    Value: 'Yes'
    AlgoTypeName: 'ctffind_ctff4'
  - Key: 'use_gctf'
    Value: 'Yes'
    AlgoTypeName: 'ctffind_gctf'
- JobType: 'relion.autopick.log'
  JobOption:
  - Key: 'do_log'
    Value: 'Yes'
    AlgoTypeName: 'autopick_log'
  - Key: 'do_log'
    Value: 'No'
    AlgoTypeName: 'autopick'
- JobType: 'relion.class2d'
  JobOption:
  - Key: 'do_em'
    Value: 'Yes'
    AlgoTypeName: 'class2d_em'
  - Key: 'do_grad'
    Value: 'Yes'
    AlgoTypeName: 'class2d_vdam'
- JobType: 'relion.class3d'
  JobOption:
  - Key: 'dont_skip_align'
    Value: 'Yes'
    AlgoTypeName: 'class3d_default'
  - Key: 'dont_skip_align'
    Value: 'No'
    AlgoTypeName: 'class3d_noalign'
- JobType: 'relion.localres.resmap'
  JobOption: 
  - Key: 'do_resmap_locres'
    Value: 'Yes'
    AlgoTypeName: 'localres_resmap'
  - Key: 'do_resmap_locres'
    Value: 'No'
    AlgoTypeName: 'localres_dummy'
- JobType: 'relion.localres.own'
  JobOption: 
  - Key: 'do_relion_locres'
    Value: 'Yes'
    AlgoTypeName: 'localres_own'
  - Key: 'do_relion_locres'
    Value: 'No'
    AlgoTypeName: 'localres_dummy'
- JobType: 'relion.select.class2dauto'
  JobOption: 
  - Key: 'do_class_ranker'
    Value: 'Yes'
    AlgoTypeName: 'select'
  - Key: 'do_class_ranker'
    Value: 'No'
    AlgoTypeName: 'select'
- JobType: 'relion.select.onvalue'
  JobOption: 
  - Key: 'do_select_values'
    Value: 'Yes'
    AlgoTypeName: 'select'
  - Key: 'do_select_values'
    Value: 'No'
    AlgoTypeName: 'select'
- JobType: 'relion.select.split'
  JobOption:
  - Key: 'do_split'
    Value: 'Yes'
    AlgoTypeName: 'select'
  - Key: 'do_split'
    Value: 'No'
    AlgoTypeName: 'select'
- JobType: 'relion.select.removeduplicates'
  JobOption:
  - Key: 'do_remove_duplicates'
    Value: 'Yes'
    AlgoTypeName: 'select'
  - Key: 'do_remove_duplicates'
    Value: 'No'
    AlgoTypeName: 'select'
- JobType: 'relion.external'
  JobOption:
  - Key: 'queuename'
    Value: 'cryolo'
    AlgoTypeName: 'external_cryolo'
  - Key: 'queuename'
    Value: 'select3d'
    AlgoTypeName: 'external_select3d'
  - Key: 'queuename'
    Value: 'bfactor'
    AlgoTypeName: 'external_bfactor_plot'
  - Key: 'queuename'
    Value: 'stack_split'
    AlgoTypeName: 'external_stack_split'
  - Key: 'queuename'
    Value: 'result_merge'
    AlgoTypeName: 'external_result_merge'