### Do not Change ####
# item_tabale
CTFFIND4Executable: fn_ctffind_exe
GctfExecutable: fn_gctf_exe
MOTIONCOR2Executable: fn_motioncor2_exe
ResMapExecutable: fn_resmap
PythonExecutable: python_exe 
SelectClass3DExecutable: fn_exe
CrYOLOExecutable: fn_exe 
CrYOLORepo: param1_value
