- AlgoLevel: motioncorr_own
  Settings:
    PrereadParticles: 'JSE_NOT_APPLICABLE_PARALLEL'
    WhichGpusToUse: ''
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: '24'
    NumberOfThreads: '8'
    NumberOfNodes: '1'
    MinimumDedicatedCores: '24'
    AdditionalArguments: '"--do_at_most \$\$GTF_motioncorr_do_at_most"'
- AlgoLevel: motioncorr_mocor2_GPU
  Settings:
    PrereadParticles: 'JSE_NOT_APPLICABLE_PARALLEL'
    WhichGpusToUse: '0:1:2:3'
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: '4'
    NumberOfThreads: '1'
    NumberOfNodes: '1'
    MinimumDedicatedCores: '4'
    AdditionalArguments: '""'
- AlgoLevel: ctffind_ctff4
  Settings:
    PrereadParticles: 'JSE_NOT_APPLICABLE_PARALLEL'
    WhichGpusToUse: ''
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: '24'
    NumberOfThreads: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfNodes: '1'
    MinimumDedicatedCores: '24'
    AdditionalArguments: '""'
- AlgoLevel: ctffind_gctf_GPU
  Settings:
    PrereadParticles: 'JSE_NOT_APPLICABLE_PARALLEL'
    WhichGpusToUse: '0:1:2:3'
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: '4'
    NumberOfThreads: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfNodes: '1'
    MinimumDedicatedCores: '4'
    AdditionalArguments: '""'
- AlgoLevel: autopick_log
  Settings:
    PrereadParticles: 'JSE_NOT_APPLICABLE_PARALLEL'
    WhichGpusToUse: ''
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: '24'
    NumberOfThreads: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfNodes: '1'
    MinimumDedicatedCores: '24'
    AdditionalArguments: '""'
- AlgoLevel: external_cryolo_GPU
  Settings:
    PrereadParticles: 'JSE_NOT_APPLICABLE_PARALLEL'
    WhichGpusToUse: 'JSE_NOT_APPLICABLE_PARALLEL'
    Param3Value: '0,1,2,3,4,5,6,7'
    NumberOfMpi: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfThreads: '1'
    NumberOfNodes: '1'
    MinimumDedicatedCores: '1'
    AdditionalArguments: '""'
- AlgoLevel: extract
  Settings:
    PrereadParticles: 'JSE_NOT_APPLICABLE_PARALLEL'
    WhichGpusToUse: 'JSE_NOT_APPLICABLE_PARALLEL'
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: '24'
    NumberOfThreads: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfNodes: '1'
    MinimumDedicatedCores: '24'
    AdditionalArguments: '""'
- AlgoLevel: class2d_vdam_GPU
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: '0,1,2,3'
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: '1'
    NumberOfThreads: '4'
    NumberOfNodes: '1'
    MinimumDedicatedCores: '1'
    AdditionalArguments: '""'
- AlgoLevel: class2d_em_GPU
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: '0:1:2:3'
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: '129'
    NumberOfThreads: '3'
    NumberOfNodes: '8'
    MinimumDedicatedCores: '16'
    AdditionalArguments: '"--fast_subsets"'
- AlgoLevel: class2d_em_CPU
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: 'JSE_NOT_APPLICABLE_PARALLEL'
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: '65'
    NumberOfThreads: '12'
    NumberOfNodes: 4'
    MinimumDedicatedCores: '16'
    AdditionalArguments: '"--fast_subsets --cpu"'
- AlgoLevel: initialmodel_GPU
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: '0,1,2,3'
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: '1'
    NumberOfThreads: '8'
    NumberOfNodes: '1'
    MinimumDedicatedCores: '1'
    AdditionalArguments: '""'
- AlgoLevel: maskcreate
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: 'JSE_NOT_APPLICABLE_PARALLEL'
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfThreads: '192'
    NumberOfNodes: '1'
    MinimumDedicatedCores: '1'
    AdditionalArguments: '""'
- AlgoLevel: class3d_default_GPU
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: '0:1:2:3:4:5:6:7:0:1:2:3:4:5:6:7'
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: '17'
    NumberOfThreads: '6'
    NumberOfNodes: '2'
    MinimumDedicatedCores: '9'
    AdditionalArguments: '""'
- AlgoLevel: class3d_default_CPU
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: '""'
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: '63'
    NumberOfThreads: '12'
    NumberOfNodes: '4'
    MinimumDedicatedCores: '16'
    AdditionalArguments: '--cpu'
- AlgoLevel: class3d_noalign
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: '""'
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: '25'
    NumberOfThreads: '7'
    NumberOfNodes: '1'
    MinimumDedicatedCores: '25'
    AdditionalArguments: '""'
- AlgoLevel: external_select3d
  Settings:
    PrereadParticles: 'JSE_NOT_APPLICABLE_PARALLEL'
    WhichGpusToUse: 'JSE_NOT_APPLICABLE_PARALLEL'
    Param3Value: '""'
    NumberOfMpi: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfThreads: '1'
    NumberOfNodes: '0'
    MinimumDedicatedCores: '0'
    AdditionalArguments: '""'
- AlgoLevel: refine3d_GPU
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: '0:1:2:3:4:5:6:7'
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: '9'
    NumberOfThreads: '6'
    NumberOfNodes: '1'
    MinimumDedicatedCores: '9'
    AdditionalArguments: '""'
- AlgoLevel: refine3d_CPU
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: '""'
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: '63'
    NumberOfThreads: '12'
    NumberOfNodes: '4'
    MinimumDedicatedCores: '16'
    AdditionalArguments: '--cpu'
- AlgoLevel: postprocess
  Settings:
    PrereadParticles: 'JSE_NOT_APPLICABLE_PARALLEL'
    WhichGpusToUse: 'JSE_NOT_APPLICABLE_PARALLEL'
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfThreads: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfNodes: '0'
    MinimumDedicatedCores: '0'
    AdditionalArguments: '""'
- AlgoLevel: ctfrefine
  Settings:
    PrereadParticles: 'JSE_NOT_APPLICABLE_PARALLEL'
    WhichGpusToUse: 'JSE_NOT_APPLICABLE_PARALLEL'
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: '24'
    NumberOfThreads: '8'
    NumberOfNodes: '1'
    MinimumDedicatedCores: '24'
    AdditionalArguments: '""'
- AlgoLevel: polish
  Settings:
    PrereadParticles: 'JSE_NOT_APPLICABLE_PARALLEL'
    WhichGpusToUse: 'JSE_NOT_APPLICABLE_PARALLEL'
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: '16'
    NumberOfThreads: '12'
    NumberOfNodes: '1'
    MinimumDedicatedCores: '16'
    AdditionalArguments: '""'
- AlgoLevel: localres
  Settings:
    PrereadParticles: 'JSE_NOT_APPLICABLE_PARALLEL'
    WhichGpusToUse: 'JSE_NOT_APPLICABLE_PARALLEL'
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: '24'
    NumberOfThreads: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfNodes: '1'
    MinimumDedicatedCores: '24'
    AdditionalArguments: '""'
- AlgoLevel: NOQUEUE
  Settings:
    PrereadParticles: 'JSE_NOT_APPLICABLE_PARALLEL'
    WhichGpusToUse: 'JSE_NOT_APPLICABLE_PARALLEL'
    Param3Value: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfMpi: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfThreads: 'JSE_NOT_APPLICABLE_PARALLEL'
    NumberOfNodes: '0'
    MinimumDedicatedCores: '0'
    AdditionalArguments: '""'
