### Do not Change ### 
DefaultConfigFilePaths: 
  ParallelSettings: XXX_SETUP_DIR_PATH_XXX/configs/environment_dependent_tutorial/config_type_algo_trial_g6_7i_relion500.yml
  EmSettings: XXX_SETUP_DIR_PATH_XXX/configs/common_tutorial/config_em_settings.yml
  SystemSettings: XXX_SETUP_DIR_PATH_XXX/configs/environment_dependent/config_system_settings.yml
