# cs-schemes auto parameter yaml
version: 1.1

parameters:
  EM_mics_apix: 0.75
  SS_comm_lbin_angpix: 3.00
  SS_comm_mbin_angpix: 0.9375

  micrograph_size: 4090

analyses:
  - name: contour_cryoread 
    executable: /home/tmoriya/.pyenv/versions/anaconda3-2025.06-1/envs/DeepMASC/bin/python
    script    : /home/tmoriya/shared_for_all/apps/DeepMASC/contour.py
    args:
      - ["--input_map_path", "/home/tmoriya/shared_for_all/data/jair/EMPIAR10673_GPCR/PostProcess/job115/postprocess.mrc"]
      - ["--output_folder" , "$OUTDIR"]
      - ["--gpu_id"        , "0,1"]
      - ["--num_components", "2"]
      - ["--batch_size"    , "8"]
      - ["--morph_radius"  , "3"]
      - ["--mask_diameter" , "95"]
      - ["--cutoff_prob"   , "0.3"]
      # - ["--plot_all"]
      # - ["--refinement_mask"] # run gmm for quick testing
      # - ["--aggressive"]
      # - ["--debug"]
  - name: contour_size
    executable: /home/tmoriya/.pyenv/versions/anaconda3-2025.06-1/envs/dev/bin/python
    script    : /home/tmoriya/shared_for_all/apps/rln_external/volume_analysis/mask_size.py
    args:
      - ["--json"]
      - ["--mask", "$BASEDIR/contour_cryoread/prot_mask_final.mrc"]
  - name: ctf_limit
    executable: /home/tmoriya/.pyenv/versions/anaconda3-2025.06-1/envs/dev/bin/python
    script:     /home/tmoriya/shared_for_all/apps/rln_external/ctf_analysis/boxsize_analysis.py
    args:
      - ["--json"]
      - ["opt"]
      - ["--pixel_size", "1.2"]
      - ["--voltage"   , "300"]
      - ["--defocus"   , "-0.8"]
      - ["--cs"        , "2.7"]
  - name: fresnel
    executable: /home/tmoriya/.pyenv/versions/anaconda3-2025.06-1/envs/dev/bin/python
    script:     /home/tmoriya/shared_for_all/apps/rln_external/ctf_analysis/boxsize_analysis.py
    args:
      - ["--json"]
      - ["fresnel"]
      - ["--particle_diameter", "200"]
      - ["--voltage"          , "300"]
      - ["--defocus"          , "1"]
      - ["--resolution"       , "2"]
  - name: fresnel_test
    executable: /home/tmoriya/.pyenv/versions/anaconda3-2025.06-1/envs/dev/bin/python
    script:     /home/tmoriya/shared_for_all/apps/rln_external/ctf_analysis/boxsize_analysis.py
    args:
      - ["--json"]
      - ["fresnel"]
      - ["--particle_diameter", {from: "contour_size", attribute: "radius"}]
      - ["--voltage"          , "300"]
      - ["--defocus"          , "1"]
      - ["--resolution"       , "2"]