### Do not change ###
- SchemeName:
  - 11_CS_Create_Stack
  - 12_CS_AbInitReconst3D
  - 13_CS_Clean_Stack_3D
  Settings:
    CS_cryolo_threshold: 0.1 
    CS_ctf_maxres: 6.0
    CS_mics_box: 360
    CS_mics_box_0o95: 342
    CS_min_nr_parts: 200000
    CS_min_nr_mics: 2000
    CS_parts_box: 120
    CS_parts_x_coods_max: 3912
    CS_parts_x_coods_min: 180
    CS_parts_y_coods_max: 3912
    CS_parts_y_coods_min: 180
    CS_class2d_pmd: 200
    CS_abinit3D_pmd: 200
    CS_nr_2d_classes: 200
    CS_rank_threshold_class2d: 0.06
    CS_rank_threshold_abinit3D: 0.26
    CS_class3d_pmd: 220
    CS_nr_3d_classes: 4
    CS_refine3d_pmd: 220
    CS_angpix: 2.5
    CS_low_pass: 7.5 
    CS_limit_mics: 1
    CS_sym_name_initial: C1
    CS_ref3d_name: binned_ref3d_map.mrc
    CS_mask3d_name: binned_mask3d_map.mrc  
    CS_sym_name_class3d: C1
    CS_sym_name_refine3d_apo: C1
- SchemeName:
  - 2_CS_Init_Refine3D
  - 3_CS_Refine_Cycle
  - 4_CS_Res_Fish
  Settings:
    CS_duplicate_threshold: 24
    CS_mics_box: 480
    CS_mics_box_0o95: 456
    CS_parts_box: 480
    CS_parts_x_coods_max: 3852
    CS_parts_x_coods_min: 240
    CS_parts_y_coods_max: 3852
    CS_parts_y_coods_min: 240
    CS_refine3d_pmd_optimal: 300
    CS_refine3d_pmd_0o95: 378
    CS_angpix: 0.88
    CS_class3d_pmd: 300
    CS_nr_3d_classes: 2
    CS_b_factor: -50
    CS_ref3d_name: binned_ref3d_map.mrc
    CS_mask3d_name: binned_mask3d_map.mrc
    CS_sym_name_refine3d_apo: C1



