Settings:
#Common
  SS_comm_class2d_pmd: 169
  SS_comm_optimal_pmd: 166
  SS_comm_dup_thresh: 21
  SS_comm_sym_name: C1
  SS_comm_lbin_angpix: 2.49
  SS_comm_lbin_ref3d_path: Inputs_Map/ref3d_emd_21992_additional_3_align_manu_tm_lpf7o47_apix2o49_d112.mrc
  SS_comm_lbin_ref3d_name: ref3d_emd_21992_additional_3_align_manu_tm_lpf7o47_apix2o49_d112.mrc
  SS_comm_lbin_mask3d_path: Inputs_Map/mask3d_emd_21992_additional_3_align_manu_tm_lpf7o47_apix2o49_d112.mrc
  SS_comm_lbin_mask3d_name: mask3d_emd_21992_additional_3_align_manu_tm_lpf7o47_apix2o49_d112.mrc
  SS_comm_mbin_angpix: 1.0375
  SS_comm_mbin_0o95box_pmd: 260
  SS_comm_mbin_ref3d_path: Inputs_Map/ref3d_emd_21992_additional_3_align_manu_tm_lpf3o1125_apix1o0375_d288.mrc
  SS_comm_mbin_ref3d_name: ref3d_emd_21992_additional_3_align_manu_tm_lpf3o1125_apix1o0375_d288.mrc
  SS_comm_mbin_mask3d_path:  Inputs_Map/mask3d_emd_21992_additional_3_align_manu_tm_lpf3o1125_apix1o0375_d288_wo_det.mrc
  SS_comm_mbin_mask3d_name: mask3d_emd_21992_additional_3_align_manu_tm_lpf3o1125_apix1o0375_d288_wo_det.mrc
  SS_comm_mbin_imported_mask3d_path: Schemes/070_CSS_Init_Refine3D/070060_Import_mask3d/\$\$SS_comm_mbin_mask3d_name
#Common Advanced
  SS_comm_motioncorr_mics_star: Schemes/010_GTF_MotionCorr/010030_Select_mics/micrographs.star
  SS_comm_ctf_mics_star: Schemes/020_GTF_CtfFind/020030_Select_icering/micrographs.star
  SS_comm_lbin_do_preread_images: 0
  SS_comm_lbin_nr_pool: 30
  SS_comm_mbin_do_preread_images: 0
  SS_comm_mbin_nr_pool: 16
  SS_comm_class2d_classes: 200
#010_GTF_MotionCorr
  GTF_eer_grouping: 32
  GTF_gain_ref_file: GLP-1_gain.mrc 
  GTF_motioncorr_do_at_most: 99999
  GTF_motioncorr_total_max_limit: 80
#010_GTF_MotionCorr Advanced
  GTF_motioncorr_run_only_once: 1
#020_GTF_CtfFind
  GTF_ctffind_search_def_min : 3000
  GTF_ctffind_search_def_max : 20000
  GTF_ctffind_res_max_limit: 6.0
  GTF_ctffind_icering_limit: 10.0
#020_GTF_CtfFind Advanced
  GTF_ctffind_run_only_once: 1
#030_GTF_Create_Stack
  GTF_pick_do_limit_mics: 1
  GTF_pick_min_nr_mics: 2000
  GTF_pick_cryolo_thresh: 0.1
  GTF_lbin_extract_cryolo_fom: 0.1
  GTF_lbin_extract_mics_box: 336
  GTF_lbin_extract_mics_0o95box: 320
  GTF_lbin_extract_parts_box: 112
  GTF_lbin_extract_parts_x_min: 168
  GTF_lbin_extract_parts_x_max: 5592
  GTF_lbin_extract_parts_y_min: 168
  GTF_lbin_extract_parts_y_max: 3924
#030_GTF_Create_Stack Advanced
  GTF_pick_use_log_pick: 0
  GTF_pick_log_pdm_min: 200
  GTF_pick_log_pdm_max: 250
  GTF_pick_log_adjust_thresh: 0
  GTF_pick_log_upper_thresh: 999
  GTF_lbin_extract_log_fom: 0
  GTF_lbin_extract_do_fom_threshold: 1
  GTF_lbin_extract_run_only_once: 1
#040_GTF_Class2D_PMDs
  GTF_lbin_class2d_pmds_do_limit_parts: 1
  GTF_lbin_class2d_pmds_min_nr_parts: 200000
  GTF_lbin_class2d_pmds_base_pmd: 180
  GTF_lbin_class2d_pmds_pad_min: 0
  GTF_lbin_class2d_pmds_pad_max: 40
  GTF_lbin_class2d_pmds_pad_step: 20
  GTF_lbin_class2d_pmds_rank_thresh: 0.06
#040_GTF_Class2D_PMDs Advanced
  GTF_lbin_class2d_pmds_wait_prev_proc: 1
  GTF_lbin_class2d_pmds_prev_proc_exited: Schemes/030_GTF_Create_Stack/RELION_JOB_EXIT_SUCCESS
  GTF_lbin_class2d_pmds_in_parts_star: Schemes/030_GTF_Create_Stack/030060_Select_rm_bars_xy/particles.star
#050_GTF_AbInitReconst3D
  GTF_lbin_abinit3d_do_limit_parts: 1
  GTF_lbin_abinit3d_min_nr_parts: 200000
  GTF_lbin_abinit3d_pmd: 169
  GTF_lbin_abinit3d_sym_name: C1
#050_GTF_AbInitReconst3D Advanced
  GTF_lbin_abinit3d_wait_prev_proc: 1
  GTF_lbin_abinit3d_prev_proc_exited: Schemes/030_GTF_Create_Stack/RELION_JOB_EXIT_SUCCESS
  GTF_lbin_abinit3d_in_parts_star: Schemes/030_GTF_Create_Stack/030060_Select_rm_bars_xy/particles.star
  GTF_lbin_abinit3d_clean2d_cycles_max: 1
  GTF_lbin_abinit3d_clean2d_rank_thresh: 0.06
  GTF_lbin_abinit3d_rank_thresh: 0.26
  GTF_lbin_abinit3d_do_run_C1: 1
#060_CSS_Clean_Stack_3D
  CSS_lbin_center3d_do_limit_parts: 1
  CSS_lbin_center3d_min_nr_parts: 400000
  CSS_lbin_center3d_class3d_use_mask3d: 1
  CSS_lbin_center3d_class3d_lpf: 30
  CSS_lbin_center3d_class3d_sym: C1
  CSS_lbin_center3d_class3d_classes: 3
  CSS_lbin_center3d_refine3d_use_mask3d: 1
  CSS_lbin_center3d_refine3d_sym_name: C1
  CSS_lbin_center3d_postproc_adhoc_lpf: 7.47
#060_CSS_Clean_Stack_3D Advanced
  CSS_lbin_center3d_wait_prev_proc: 1
  CSS_lbin_center3d_prev_proc_exited: Schemes/030_GTF_Create_Stack/RELION_JOB_EXIT_SUCCESS
  CSS_lbin_center3d_parts_star: Schemes/030_GTF_Create_Stack/030060_Select_rm_bars_xy/particles.star
  CSS_lbin_center3d_clean2d_cycles_max: 0
  CSS_lbin_center3d_clean2d_rank_thresh: 0.06
  CSS_lbin_center3d_class3d_conts_max: 3
  CSS_lbin_center3d_class3d_iter_step: 25
  CSS_lbin_center3d_class3d_offset_factor: 4
  CSS_lbin_center3d_class3d_do_fast_subsets: 1
  CSS_lbin_center3d_class3d_cont_stars: run_it000_optimiser.star,run_it025_optimiser.star,run_it050_optimiser.star
  CSS_lbin_center3d_class3d_parts_star: Schemes/060_CSS_Clean_Stack_3D/060060_Class3D/run_it075_data.star
#070_CSS_Init_Refine3D
  CSS_mbin_reextract_mics_box: 360
  CSS_mbin_reextract_mics_0o95box: 342
  CSS_mbin_reextract_parts_box: 288
  CSS_mbin_reextract_parts_x_min: 180
  CSS_mbin_reextract_parts_x_max: 5580
  CSS_mbin_reextract_parts_y_min: 180
  CSS_mbin_reextract_parts_y_max: 3912
#070_CSS_Init_Refine3D Advanced
  CSS_mbin_reextract_wait_prev_proc: 1
  CSS_mbin_reextract_prev_proc_exited: Schemes/060_CSS_Clean_Stack_3D/RELION_JOB_EXIT_SUCCESS
  CSS_mbin_reextract_refined_star: Schemes/060_CSS_Clean_Stack_3D/060080_Refine3D_global/run_data.star
#080_CSS_PPRefine_Cycle
  CSS_mbin_pprefine_cycles_max: 2
  CSS_mbin_pprefine_stop_at_ctfrefine: 1
#080_CSS_PPRefine_Cycle Advanced
  CSS_mbin_pprefine_wait_prev_proc: 1
  CSS_mbin_pprefine_prev_proc_exited: Schemes/070_CSS_Init_Refine3D/RELION_JOB_EXIT_SUCCESS
  CSS_mbin_pprefine_refined_star: Schemes/070_CSS_Init_Refine3D/070090_Refine3D_local/run_data.star
  CSS_mbin_pprefine_postproc_star: Schemes/070_CSS_Init_Refine3D/070100_PostProcess_local/postprocess.star
  CSS_mbin_pprefine_ref3d: Schemes/070_CSS_Init_Refine3D/070090_Refine3D_local/run_class001.mrc
#090_CSS_Res_Fish_3D
  CSS_mbin_resfish3d_refined_star: Schemes/080_CSS_PPRefine_Cycle/080040_Refine3D_ctfrefine/run_data.star
  CSS_mbin_resfish3d_ref3d: Schemes/080_CSS_PPRefine_Cycle/080040_Refine3D_ctfrefine/run_class001.mrc
  CSS_mbin_resfish3d_classes: 2
  CSS_mbin_resfish3d_tval: 256
  CSS_mbin_resfish3d_locres_bfactor: -67
#090_CSS_Res_Fish_3D Advanced
  CSS_mbin_resfish3d_wait_prev_proc: 1
  CSS_mbin_resfish3d_prev_proc_exited: Schemes/080_CSS_PPRefine_Cycle/RELION_JOB_EXIT_SUCCESS
  CSS_mbin_resfish3d_do_fast_subsets: 1
#100_CSS_Bfactor_Plot
  CSS_mbin_bfactor_refine3d_job: Schemes/090_CSS_Res_Fish_3D/090050_Refine3D_local/
  CSS_mbin_bfactor_postproc_job: Schemes/090_CSS_Res_Fish_3D/090060_PostProcess_local/
  CSS_mbin_bfactor_min_nr_parts: 1100
  CSS_mbin_bfactor_max_nr_parts: 4400
#100_CSS_Bfactor_Plot Advanced
  CSS_mbin_bfactor_wait_prev_proc: 1
  CSS_mbin_bfactor_prev_proc_exited: Schemes/090_CSS_Res_Fish_3D/RELION_JOB_EXIT_SUCCESS
