Settings:
#Common
  SS_comm_class2d_pmd: 200
  SS_comm_optimal_pmd: 200
  SS_comm_dup_thresh: 25
  SS_comm_sym_name: D2
  SS_comm_lbin_angpix: 3.54
  SS_comm_lbin_ref3d_path: ref3d_beta_galactosidase_apix3o54_d64.mrc
  SS_comm_lbin_ref3d_name: ref3d_beta_galactosidase_apix3o54_d64.mrc
  SS_comm_lbin_mask3d_path: mask3d_beta_galactosidase_apix3o54_d64.mrc
  SS_comm_lbin_mask3d_name: mask3d_beta_galactosidase_apix3o54_d64.mrc
  SS_comm_mbin_angpix: 1.244
  SS_comm_mbin_0o95box_pmd: 303
  SS_comm_mbin_ref3d_path: ref3d_beta_galactosidase_apix1o244_d256.mrc
  SS_comm_mbin_ref3d_name: ref3d_beta_galactosidase_apix1o244_d256.mrc
  SS_comm_mbin_mask3d_path: mask3d_beta_galactosidase_apix1o244_d256.mrc
  SS_comm_mbin_mask3d_name: mask3d_beta_galactosidase_apix1o244_d256.mrc
  SS_comm_mbin_imported_mask3d_path: Schemes/070_CSS_Init_Refine3D/070060_Import_mask3d/\$\$SS_comm_mbin_mask3d_name
#Common Advanced
  SS_comm_wait_prev_proc_gtf_debug: 0
  SS_comm_wait_prev_proc: 1
  SS_comm_motioncorr_mics_star: Schemes/010_GTF_MotionCorr/010030_Select_mics/micrographs.star
  SS_comm_ctf_mics_star: Schemes/020_GTF_CtfFind/020020_Select_mics/micrographs.star
  SS_comm_class2d_classes: 100
#010_GTF_MotionCorr
  GTF_eer_grouping: 32
  GTF_gain_ref_file: Micrographs/20240325_112241_EER_GainReference.gain
  GTF_motioncorr_do_at_most: 99999
  GTF_motioncorr_total_max_limit: 80
#020_GTF_CtfFind
  GTF_ctffind_search_def_min : 5000
  GTF_ctffind_search_def_max : 50000
  GTF_ctffind_res_max_limit: 6.0
#030_GTF_Create_Stack
  GTF_pick_do_limit_mics: 0
  GTF_pick_min_nr_mics: 24
  GTF_pick_cryolo_thresh: 0.1
  GTF_lbin_extract_mics_box: 256
  GTF_lbin_extract_mics_0o95box: 200
  GTF_lbin_extract_parts_box: 64
  GTF_lbin_extract_parts_x_min: 128
  GTF_lbin_extract_parts_x_max: 3582
  GTF_lbin_extract_parts_y_min: 128
  GTF_lbin_extract_parts_y_max: 3710
#030_GTF_Create_Stack Advanced
  GTF_pick_use_log_pick: 0
  GTF_pick_log_pdm_min: 100
  GTF_pick_log_pdm_max: 160
  GTF_pick_log_adjust_thresh: 0.25
  GTF_pick_log_upper_thresh: 5
#040_GTF_Class2D_PMDs
  GTF_lbin_class2d_pmds_in_parts_star: Schemes/030_GTF_Create_Stack/030060_Select_rm_bars_xy/particles.star
  GTF_lbin_class2d_pmds_do_limit_parts: 1
  GTF_lbin_class2d_pmds_min_nr_parts: 4000
  GTF_lbin_class2d_pmds_base_pmd: 180
  GTF_lbin_class2d_pmds_pad_min: 0
  GTF_lbin_class2d_pmds_pad_max: 40
  GTF_lbin_class2d_pmds_pad_step: 20
  GTF_lbin_class2d_pmds_rank_thresh: 0.06
#050_GTF_AbInitReconst3D
  GTF_lbin_abinit3d_do_limit_parts: 0
  GTF_lbin_abinit3d_min_nr_parts: 4000
  GTF_lbin_abinit3d_pmd: 200
  GTF_lbin_abinit3d_sym_name: D2
#050_GTF_AbInitReconst3D Advanced
  GTF_lbin_abinit3d_in_parts_star: Schemes/030_GTF_Create_Stack/030060_Select_rm_bars_xy/particles.star
  GTF_lbin_abinit3d_clean2d_cycles_max: 1
  GTF_lbin_abinit3d_clean2d_rank_thresh: 0.06
  GTF_lbin_abinit3d_rank_thresh: 0.26
  GTF_lbin_abinit3d_do_run_C1: 1
#060_CSS_Clean_Stack_3D
  CSS_lbin_center3d_do_limit_parts: 0
  CSS_lbin_center3d_min_nr_parts: 4000
  CSS_lbin_center3d_class3d_use_mask3d: 1
  CSS_lbin_center3d_class3d_lpf: 30
  CSS_lbin_center3d_class3d_sym: C1
  CSS_lbin_center3d_class3d_classes: 4
  CSS_lbin_center3d_refine3d_use_mask3d: 1
  CSS_lbin_center3d_refine3d_sym_name: C1
  CSS_lbin_center3d_postproc_adhoc_lpf: 10.62
#060_CSS_Clean_Stack_3D Advanced
  CSS_lbin_center3d_parts_star: Schemes/030_GTF_Create_Stack/030060_Select_rm_bars_xy/particles.star
  CSS_lbin_center3d_clean2d_cycles_max: 0
  CSS_lbin_center3d_clean2d_rank_thresh: 0.06
  CSS_lbin_center3d_class3d_conts_max: 1
  CSS_lbin_center3d_class3d_iter_step: 25
  CSS_lbin_center3d_class3d_offset_factor: 1
  CSS_lbin_center3d_class3d_do_fast_subsets: 1
  CSS_lbin_center3d_class3d_cont_stars: run_it000_optimiser.star
  CSS_lbin_center3d_class3d_parts_star: Schemes/060_CSS_Clean_Stack_3D/060060_Class3D/run_it025_data.star
#070_CSS_Init_Refine3D
  CSS_mbin_reextract_mics_box: 360
  CSS_mbin_reextract_mics_0o95box: 342
  CSS_mbin_reextract_parts_box: 256
  CSS_mbin_reextract_parts_x_min: 180
  CSS_mbin_reextract_parts_x_max: 3530
  CSS_mbin_reextract_parts_y_min: 180
  CSS_mbin_reextract_parts_y_max: 3658
#070_CSS_Init_Refine3D Advanced
  CSS_mbin_reextract_refined_star: Schemes/060_CSS_Clean_Stack_3D/060080_Refine3D_global/run_data.star
#080_CSS_PPRefine_Cycle
  CSS_mbin_pprefine_refined_star: Schemes/070_CSS_Init_Refine3D/070090_Refine3D_local/run_data.star
  CSS_mbin_pprefine_postproc_star: Schemes/070_CSS_Init_Refine3D/070100_PostProcess_local/postprocess.star
  CSS_mbin_pprefine_ref3d: Schemes/070_CSS_Init_Refine3D/070090_Refine3D_local/run_class001.mrc
#080_CSS_PPRefine_Cycle Advanced
  CSS_mbin_pprefine_cycles_max: 2
#090_CSS_Res_Fish_3D
  CSS_mbin_resfish3d_classes: 2
  CSS_mbin_resfish3d_tval: 16
  CSS_mbin_resfish3d_locres_bfactor: -30
#090_CSS_Res_Fish_3D Advanced
  CSS_mbin_resfish3d_refined_star: Schemes/080_CSS_PPRefine_Cycle/080070_Refine3D_polish/run_data.star
  CSS_mbin_resfish3d_ref3d: Schemes/080_CSS_PPRefine_Cycle/080070_Refine3D_polish/run_class001.mrc
  CSS_mbin_resfish3d_do_fast_subsets: 1
