- DeviceLevel: g5-vcpu192-gpu8
  Settings:
    ScratchDirectory: '/scratch'
    UseGpu: 'Yes'
    Partition: 'g5-vcpu192-gpu8'
- DeviceLevel: g5-vcpu48-gpu4
  Settings:
    ScratchDirectory: '/scratch'
    UseGpu: 'Yes'
    Partition: 'g5-vcpu48-gpu4'
- DeviceLevel: g4dn-vcpu96-gpu8
  Settings:
    ScratchDirectory: '/scratch'
    UseGpu: 'Yes'
    Partition: 'g4dn-vcpu96-gpu8'
- DeviceLevel: g4dn-vcpu48-gpu4
  Settings:
    ScratchDirectory: '/scratch'
    UseGpu: 'Yes'
    Partition: 'g4dn-vcpu48-gpu4'
- DeviceLevel: c6i-vcpu128-gpu0
  Settings:
    ScratchDirectory: '""'
    UseGpu: 'No'
    Partition: 'c6i-vcpu128-gpu0'
- DeviceLevel: NOQUEUE_GPU
  Settings:
    ScratchDirectory: '/scratch/gotofly'
    UseGpu: 'Yes'
    Partition: 'invalid_partition'
- DeviceLevel: NOQUEUE_CPU
  Settings:
    ScratchDirectory: '""'
    UseGpu: 'No'
    Partition: 'invalid_partition'
