### Do not Change ### 
NonEditableAlertDisplay: True
JobStarSettings: 
  LevelFile: 
    SubmissionLevel: XXX_SETUP_DIR_PATH_XXX/configs/environment_dependent/config_level_submission_relion500.yml
    DeviceLevel: XXX_SETUP_DIR_PATH_XXX/configs/environment_dependent/config_level_device.yml
    AlgoLevel: XXX_SETUP_DIR_PATH_XXX/configs/environment_dependent/config_level_algo_empiar10673_gpcr_g6_7i.yml
  CombinationSettings:
  - AlgoType: algo_type_import
    SubmissionLevel: NOQUEUE
    DeviceLevel: NOQUEUE_CPU
    AlgoLevel: NOQUEUE
  - AlgoType: algo_type_motioncorr_own
    SubmissionLevel: intel-intelmpi-cpu_axcore
    DeviceLevel: m7i-vcpu192-gpu0
    AlgoLevel: motioncorr_own
  - AlgoType: algo_type_motioncorr_mocor2
    SubmissionLevel: gcc-intelmpi-gpu
    DeviceLevel: g6-vcpu48-gpu4
    AlgoLevel: motioncorr_mocor2_GPU
  - AlgoType: algo_type_ctffind_ctff4
    SubmissionLevel: intel-intelmpi-cpu_axcore
    DeviceLevel: m7i-vcpu192-gpu0
    AlgoLevel: ctffind_ctff4
  - AlgoType: algo_type_ctffind_gctf
    SubmissionLevel: gcc-intelmpi-gpu
    DeviceLevel: g6-vcpu48-gpu4
    AlgoLevel: ctffind_gctf_GPU
  - AlgoType: algo_type_autopick_log
    SubmissionLevel: intel-intelmpi-cpu_axcore
    DeviceLevel: m7i-vcpu192-gpu0
    AlgoLevel: autopick_log
  - AlgoType: algo_type_extract
    SubmissionLevel: intel-intelmpi-cpu_axcore
    DeviceLevel: c7i-vcpu192-gpu0
    AlgoLevel: extract
  - AlgoType: algo_type_class2d_em
    SubmissionLevel: gcc-intelmpi-gpu
    DeviceLevel: g6-vcpu48-gpu4
    AlgoLevel: class2d_em_GPU
  - AlgoType: algo_type_class2d_vdam
    SubmissionLevel: gcc-intelmpi-gpu
    DeviceLevel: g6-vcpu48-gpu4
    AlgoLevel: class2d_vdam_GPU
  - AlgoType: algo_type_initialmodel
    SubmissionLevel: gcc-intelmpi-gpu
    DeviceLevel: g6-vcpu48-gpu4
    AlgoLevel: initialmodel_GPU
  - AlgoType: algo_type_class3d_default
    SubmissionLevel: gcc-intelmpi-gpu
    DeviceLevel: g6-vcpu192-gpu8
    AlgoLevel: class3d_default_GPU
  - AlgoType: algo_type_class3d_noalign
    SubmissionLevel: intel-intelmpi-cpu_axcore
    DeviceLevel: c7i-vcpu192-gpu0
    AlgoLevel: class3d_noalign
  - AlgoType: algo_type_refine3d
    SubmissionLevel: gcc-intelmpi-gpu
    DeviceLevel: g6-vcpu192-gpu8
    AlgoLevel: refine3d_GPU
  - AlgoType: algo_type_select
    SubmissionLevel: NOQUEUE
    DeviceLevel: NOQUEUE_CPU
    AlgoLevel: NOQUEUE
  - AlgoType: algo_type_ctfrefine
    SubmissionLevel: intel-intelmpi-cpu_axcore
    DeviceLevel: m7i-vcpu192-gpu0
    AlgoLevel: ctfrefine
  - AlgoType: algo_type_polish
    SubmissionLevel: intel-intelmpi-cpu_axcore
    DeviceLevel: m7i-vcpu192-gpu0
    AlgoLevel: polish
  - AlgoType: algo_type_maskcreate
    SubmissionLevel: intel-intelmpi-cpu_axcore
    DeviceLevel: c7i-vcpu192-gpu0
    AlgoLevel: maskcreate
  - AlgoType: algo_type_postprocess
    SubmissionLevel: NOQUEUE
    DeviceLevel: NOQUEUE_CPU
    AlgoLevel: postprocess
  - AlgoType: algo_type_localres_resmap
    SubmissionLevel: NOQUEUE
    DeviceLevel: NOQUEUE_CPU
    AlgoLevel: localres_resmap
  - AlgoType: algo_type_localres_own
    SubmissionLevel: intel-intelmpi-cpu_axcore
    DeviceLevel: m7i-vcpu192-gpu0
    AlgoLevel: localres_own
  - AlgoType: algo_type_external_cryolo
    SubmissionLevel: gcc-intelmpi-gpu
    DeviceLevel: g6-vcpu192-gpu8
    AlgoLevel: external_cryolo_GPU
  - AlgoType: algo_type_external_select3d
    SubmissionLevel: NOQUEUE
    DeviceLevel: NOQUEUE_CPU
    AlgoLevel: external_select3d
  - AlgoType: algo_type_external_bfactor_plot
    SubmissionLevel: NOQUEUE
    DeviceLevel: NOQUEUE_CPU
    AlgoLevel: external_bfactor_plot
  - AlgoType: algo_type_external_result_merge
    SubmissionLevel: NOQUEUE
    DeviceLevel: NOQUEUE_CPU
    AlgoLevel: external_result_merge
