### Do not Change ### 
LevelFile: 
  SubmissionLevel: ../../configs/gotocloud/config_level_submission.yml
  DeviceLevel: ../../configs/gotocloud/config_level_device.yml
  AlgoLevel: ../../configs/gotocloud/config_level_algo.yml
CombinationSettings:
- AlgoType: algo_type_motioncorr_own
  SubmissionLevel: GPU
  DeviceLevel: c6i-vcpu128-gpu0
  AlgoLevel: motioncorr_own
- AlgoType: algo_type_motioncorr_mocor2
  SubmissionLevel: GPU
  DeviceLevel: g5-vcpu48-gpu4
  AlgoLevel: motioncorr_mocor2_GPU
- AlgoType: algo_type_ctffind_ctff4
  SubmissionLevel: GPU
  DeviceLevel: c6i-vcpu128-gpu0
  AlgoLevel: ctffind_ctff4
- AlgoType: algo_type_ctffind_gctf
  SubmissionLevel: GPU
  DeviceLevel: g5-vcpu48-gpu4
  AlgoLevel: ctffind_gctf_GPU
- AlgoType: algo_type_external_cryolo
  SubmissionLevel: GPU
  DeviceLevel: g5-vcpu192-gpu8
  AlgoLevel: external_cryolo_GPU
- AlgoType: algo_type_extract
  SubmissionLevel: GPU
  DeviceLevel: c6i-vcpu128-gpu0
  AlgoLevel: extract
- AlgoType: algo_type_class2d_vdam
  SubmissionLevel: GPU
  DeviceLevel: g5-vcpu48-gpu4
  AlgoLevel: class2d_vdam_GPU
- AlgoType: algo_type_class2d_em
  SubmissionLevel: GPU
  DeviceLevel: g4dn-vcpu48-gpu4
  AlgoLevel: class2d_em_GPU
- AlgoType: algo_type_initialmodel
  SubmissionLevel: GPU
  DeviceLevel: g5-vcpu48-gpu4
  AlgoLevel: initialmodel_GPU
- AlgoType: algo_type_maskcreate
  SubmissionLevel: GPU
  DeviceLevel: c6i-vcpu128-gpu0
  AlgoLevel: maskcreate
- AlgoType: algo_type_class3d_default
  SubmissionLevel: GPU
  DeviceLevel: g5-vcpu48-gpu4
  AlgoLevel: class3d_default_GPU
- AlgoType: algo_type_class3d_noalign
  SubmissionLevel: GPU
  DeviceLevel: c6i-vcpu128-gpu0
  AlgoLevel: class3d_noalign
- AlgoType: algo_type_external_select3d
  SubmissionLevel: NOQUEUE
  DeviceLevel: NOQUEUE_CPU
  AlgoLevel: external_select3d
- AlgoType: algo_type_refine3d
  SubmissionLevel: GPU
  DeviceLevel: g5-vcpu48-gpu4
  AlgoLevel: refine3d_GPU
- AlgoType: algo_type_postprocess
  SubmissionLevel: NOQUEUE
  DeviceLevel: NOQUEUE_CPU
  AlgoLevel: postprocess
- AlgoType: algo_type_ctfrefine
  SubmissionLevel: GPU
  DeviceLevel: c6i-vcpu128-gpu0
  AlgoLevel: ctfrefine
- AlgoType: algo_type_polish
  SubmissionLevel: GPU
  DeviceLevel: c6i-vcpu128-gpu0
  AlgoLevel: polish
- AlgoType: algo_type_localres_own
  SubmissionLevel: GPU
  DeviceLevel: c6i-vcpu128-gpu0
  AlgoLevel: localres

