- AlgoLevel: motioncorr_own
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: 'PS_NOT_APPLICABLE'
    Param3Value: 'PS_NOT_APPLICABLE'
    NumberOfMpi: '64'
    NumberOfThreads: '32'
    MinimumDedicatedCores: '4'
    AdditionalArguments: '"--do_at_most $$do_at_most"'
- AlgoLevel: motioncorr_mocor2_GPU
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: '0:1:2:3'
    Param3Value: '0:1:2:3'
    NumberOfMpi: '4'
    NumberOfThreads: '1'
    MinimumDedicatedCores: '4'
    AdditionalArguments: '"--do_at_most $$do_at_most"'
- AlgoLevel: ctffind_ctff4
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: 'PS_NOT_APPLICABLE'
    Param3Value: 'PS_NOT_APPLICABLE'
    NumberOfMpi: '64'
    NumberOfThreads: '1'
    MinimumDedicatedCores: '4'
    AdditionalArguments: '""'
- AlgoLevel: ctffind_gctf_GPU
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: '0:1:2:3'
    Param3Value: '0:1:2:3'
    NumberOfMpi: '4'
    NumberOfThreads: '1'
    MinimumDedicatedCores: '4'
    AdditionalArguments: '""'
- AlgoLevel: external_cryolo_GPU
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: '0,1,2,3,4,5,6,7'
    Param3Value: '0,1,2,3,4,5,6,7'
    NumberOfMpi: '1'
    NumberOfThreads: '1'
    MinimumDedicatedCores: '1'
    AdditionalArguments: '""'
- AlgoLevel: extract
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: 'PS_NOT_APPLICABLE'
    Param3Value: 'PS_NOT_APPLICABLE'
    NumberOfMpi: '128'
    NumberOfThreads: '1'
    MinimumDedicatedCores: '128'
    AdditionalArguments: '""'
- AlgoLevel: class2d_vdam_GPU
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: '0,1,2,3'
    Param3Value: '0,1,2,3'
    NumberOfMpi: '1'
    NumberOfThreads: '4'
    MinimumDedicatedCores: '1'
    AdditionalArguments: '""'
- AlgoLevel: class2d_em_GPU
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: '0:1:2:0:1:2:3:0:1:2:3:0:1:2'
    Param3Value: '0:1:2:0:1:2:3:0:1:2:3:0:1:2'
    NumberOfMpi: '15'
    NumberOfThreads: '6'
    MinimumDedicatedCores: '4'
    AdditionalArguments: '"--fast_subsets"'
- AlgoLevel: class2d_em_CPU
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: 'PS_NOT_APPLICABLE'
    Param3Value: 'PS_NOT_APPLICABLE'
    NumberOfMpi: '63'
    NumberOfThreads: '16'
    MinimumDedicatedCores: '8'
    AdditionalArguments: '"--fast_subsets --cpu"'
- AlgoLevel: initialmodel_GPU
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: '0,1,2,3'
    Param3Value: '0,1,2,3'
    NumberOfMpi: '1'
    NumberOfThreads: '4'
    MinimumDedicatedCores: '1'
    AdditionalArguments: '""'
- AlgoLevel: maskcreate
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: 'PS_NOT_APPLICABLE'
    Param3Value: 'PS_NOT_APPLICABLE'
    NumberOfMpi: '1'
    NumberOfThreads: '128'
    MinimumDedicatedCores: '1'
    AdditionalArguments: '""'
- AlgoLevel: class3d_default_GPU
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: '0:1:2:0:1:2:3:0:1:2:3:0:1:2'
    Param3Value: '0:1:2:0:1:2:3:0:1:2:3:0:1:2'
    NumberOfMpi: '15'
    NumberOfThreads: '6'
    MinimumDedicatedCores: '4'
    AdditionalArguments: '""'
- AlgoLevel: class3d_default_CPU
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: 'PS_NOT_APPLICABLE'
    Param3Value: 'PS_NOT_APPLICABLE'
    NumberOfMpi: '63'
    NumberOfThreads: '16'
    MinimumDedicatedCores: '8'
    AdditionalArguments: '--cpu'
- AlgoLevel: class3d_noalign
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: 'PS_NOT_APPLICABLE'
    Param3Value: 'PS_NOT_APPLICABLE'
    NumberOfMpi: '63'
    NumberOfThreads: '32'
    MinimumDedicatedCores: '4'
    AdditionalArguments: '""'
- AlgoLevel: external_select3d
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: 'PS_NOT_APPLICABLE'
    Param3Value: 'PS_NOT_APPLICABLE'
    NumberOfMpi: '1'
    NumberOfThreads: '1'
    MinimumDedicatedCores: '1'
    AdditionalArguments: 'PS_NOT_APPLICABLE'
- AlgoLevel: refine3d_GPU
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: '0:1:2:3:0:1:2:3'
    Param3Value: '0:1:2:3:0:1:2:3'
    NumberOfMpi: '9'
    NumberOfThreads: '6'
    MinimumDedicatedCores: '5'
    AdditionalArguments: '""'
- AlgoLevel: refine3d_CPU
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: 'PS_NOT_APPLICABLE'
    Param3Value: 'PS_NOT_APPLICABLE'
    NumberOfMpi: '63'
    NumberOfThreads: '16'
    MinimumDedicatedCores: '8'
    AdditionalArguments: '--cpu'
- AlgoLevel: postprocess
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: 'PS_NOT_APPLICABLE'
    Param3Value: 'PS_NOT_APPLICABLE'
    NumberOfMpi: '1'
    NumberOfThreads: '1'
    MinimumDedicatedCores: '1'
    AdditionalArguments: '""'
- AlgoLevel: ctfrefine
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: 'PS_NOT_APPLICABLE'
    Param3Value: 'PS_NOT_APPLICABLE'
    NumberOfMpi: '16'
    NumberOfThreads: '32'
    MinimumDedicatedCores: '4'
    AdditionalArguments: '""'
- AlgoLevel: polish
  Settings:
    PrereadParticles: 'No'
    WhichGpusToUse: 'PS_NOT_APPLICABLE'
    Param3Value: 'PS_NOT_APPLICABLE'
    NumberOfMpi: '8'
    NumberOfThreads: '64'
    MinimumDedicatedCores: '2'
    AdditionalArguments: '""'
- AlgoLevel: localres
  Settings:
    PrereadParticles: 'PS_NOT_APPLICABLE'
    WhichGpusToUse: 'PS_NOT_APPLICABLE'
    Param3Value: 'PS_NOT_APPLICABLE'
    NumberOfMpi: '256'
    NumberOfThreads: 'PS_NOT_APPLICABLE'
    MinimumDedicatedCores: '16'
    AdditionalArguments: '""'

