### Do not Change ### 
DefaultConfigFilePaths: 
  ParallelSettings: /lustre1/emsystem/apps/schemes_editor/configs/environment_dependent/config_type_algo.yml
  EmSettings: /lustre1/emsystem/apps/schemes_editor/configs/common/config_em_settings_kek_krios_tiff.yml
  SystemSettings: /lustre1/emsystem/apps/schemes_editor/configs/environment_dependent/config_system_settings.yml
