- SubmissionLevel: GPU
  ParallelSettings: 
    SubmitToQueue: 'Yes'
    SubmitCommand: 'sbatch'
    SubmissionScript: '/efs/em/aws_slurm_relion.sh'
- SubmissionLevel: CPU
  ParallelSettings:
    SubmitToQueue: 'Yes'
    SubmitCommand: 'sbatch'
    SubmissionScript: '/efs/em/aws_slurm_relion.sh'
- SubmissionLevel: NOQUEUE
  ParallelSettings:
    SubmitToQueue: 'No'
    SubmitCommand: '""'
    SubmissionScript: '""'
