- DeviceLevel: g5-vcpu192-gpu8
  ParallelSettings:
    ScratchDirectory: '/scratch'
    UseGpu: 'Yes'
    Partition: 'g5-vcpu192-gpu8'
- DeviceLevel: g5-vcpu48-gpu4
  ParallelSettings:
    ScratchDirectory: '/scratch'
    UseGpu: 'Yes'
    Partition: 'g5-vcpu48-gpu4'
- DeviceLevel: g4dn-vcpu96-gpu8
  ParallelSettings:
    ScratchDirectory: '/scratch'
    UseGpu: 'Yes'
    Partition: 'g4dn-vcpu96-gpu8'
- DeviceLevel: g4dn-vcpu48-gpu4
  ParallelSettings:
    ScratchDirectory: '/scratch'
    UseGpu: 'Yes'
    Partition: 'g4dn-vcpu48-gpu4'
- DeviceLevel: c7i-vcpu192-gpu0
  ParallelSettings:
    ScratchDirectory: '""'
    UseGpu: 'No'
    Partition: 'c7i-vcpu192-gpu0'
- DeviceLevel: m7i-vcpu192-gpu0
  ParallelSettings:
    ScratchDirectory: '""'
    UseGpu: 'No'
    Partition: 'm7i-vcpu192-gpu0'
- DeviceLevel: c6i-vcpu128-gpu0
  ParallelSettings:
    ScratchDirectory: '""'
    UseGpu: 'No'
    Partition: 'c6i-vcpu128-gpu0'
- DeviceLevel: NOQUEUE_GPU
  ParallelSettings:
    ScratchDirectory: '/scratch/gotofly'
    UseGpu: 'Yes'
    Partition: 'invalid_partition'
- DeviceLevel: NOQUEUE_CPU
  ParallelSettings:
    ScratchDirectory: '""'
    UseGpu: 'No'
    Partition: 'invalid_partition'
