### Do not change ###
- ComputingEnvironment: Reedbush
  ExecutableFilePath:
    CTFFIND4Executable: /lustre1/emsystem/apps/ctffind-4.1.14/ctffind 
    GctfExecutable: /lustre1/emsystem/apps/GCTF_Gautomatch_Cu10.1/GCTF_v1.18_sm30-75_cu10.1
    MOTIONCOR2Executable: /lustre1/emsystem/apps/MotionCor2/MotionCor2_1.4.7_Cuda115_12-09-2021 
    ResMapExecutable: /lustre1/emsystem/apps/ResMap/ResMap-1.1.4-linux64
    PythonExecutable: /lustre1/emsystem/apps/pyenv/versions/anaconda3-5.3.1/envs/topaz/bin/python 
    SelectClass3DExecutable: '"/lustre1/emsystem/apps/pyenv/versions/anaconda3-5.3.1/envs/topaz/bin/python /lustre1/emdata/gotofly/gtf_schemes_cs/GoToFly/SelectClass3D/gtf_relion4_run_select_class3d.py"' 
    CrYOLOExecutable: /lustre1/emsystem/apps/crYOLO/gtf_relion4_run_cryolo_system.sh 
    CrYOLORepo: /lustre1/emsystem/apps/crYOLO

- ComputingEnvironment: GoToCloud
  ExecutableFilePath:
    CTFFIND4Executable: /efs/em/ctffind-4.1.14-linux64/bin/ctffind
    GctfExecutable: /efs/em/Gctf_v1.06/bin/Gctf-v1.06_sm_20_cu7.5_x86_64
    MOTIONCOR2Executable: '""'
    ResMapExecutable: '""'
    PythonExecutable: /efs/em/pyenv/versions/anaconda3-5.3.1/envs/topaz/bin/python
    SelectClass3DExecutable: '"/efs/em/pyenv/versions/anaconda3-5.3.1/envs/cryolo-1.8.0/bin/python /fsx/GoToFly/SelectClass3D/gtf_relion4_run_select_class3d.py"'
    CrYOLOExecutable: /efs/em/crYOLO/gtf_relion4_run_cryolo_system.sh 
    CrYOLORepo: /efs/em/crYOLO

- ComputingEnvironment: CryoemWS
  ExecutableFilePath:
    CTFFIND4Executable: /home/ubuntu/ctffind-4.1.14-linux64/bin/ctffind
    GctfExecutable: '""'
    MOTIONCOR2Executable: '""'
    ResMapExecutable: '""'
    PythonExecutable: /home/ubuntu/pyenv/versions/anaconda3-5.3.1/envs/topaz/bin/python
    SelectClass3DExecutable: '""'
    CrYOLOExecutable: /efs/em/crYOLO/gtf_relion4_run_cryolo_system.sh 
    CrYOLORepo: /efs/em/crYOLO



