environment:
  env:
    python_deepmasc    : /home/tmoriya/.pyenv/versions/anaconda3-2025.06-1/envs/DeepMASC/bin/python
    python_cryoem_tools: /home/tmoriya/.pyenv/versions/anaconda3-2025.06-1/envs/dev/bin/python

  toolbox:
    cryoread_contour: 
      env    : python_deepmasc
      script : /home/tmoriya/shared_for_all/apps/DeepMASC/contour.py

    size_estimation: 
      env    : python_cryoem_tools
      script : /home/tmoriya/shared_for_all/apps/rln_external/negative_region/size_estimation.py
    
    negative_estimation: 
      env    : python_cryoem_tools
      script : /home/tmoriya/shared_for_all/apps/rln_external/negative_region/negative_estimation.py

    volume_alignment: 
      env    : python_cryoem_tools
      script : /home/tmoriya/shared_for_all/apps/rln_external/negative_region/volume_alignment.py

    boxsize_analysis:
      env    : python_cryoem_tools
      script : /home/tmoriya/shared_for_all/apps/rln_external/ctf_analysis/boxsize_analysis.py

analyses:
  - name: reference_map_contour
    script: cryoread_contour
    args:
      - ["--input_map_path", {from: input.user, attribute: reference_map_filepath}]
      - ["--output_folder",  "$OUTDIR"]
      - ["--gpu_id"        , "0,1"]
      - ["--num_components", "2"]
      - ["--batch_size"    , "8"]
      - ["--morph_radius"  , "3"]
      - ["--mask_diameter" , "95"]
      - ["--cutoff_prob"   , "0.3"]

  - name: volume_alignment
    script: volume_alignment
    args:
      - ["--volume", {from: input.user, attribute: reference_map_filepath}]
      - ["--mask",   "$BASEDIR/reference_map_contour/prot_mask_final.mrc"]
      - ["--json"]
      - ["--save"]
      - ["--verbose"]
      - ["--output-dir", "$OUTDIR"]

css_config:
  inputs:
    ref3d_path : {from: analyses.volume_alignment, attribute: volume}
    mask3d_path: {from: analyses.volume_alignment, attribute: mask}

  params_to_compute:
    - SS_comm_lbin_ref3d_path
    - SS_comm_lbin_ref3d_name
    - SS_comm_lbin_mask3d_path
    - SS_comm_lbin_mask3d_name

user_inputs:
  reference_map_filepath:   "/home/tmoriya/shared_for_all/data/jair/EMPIAR10673_GPCR/PostProcess/job115/postprocess.mrc"

