analyses:
  - name: reference_map_contour
    script: cryoread_contour
    args:
      - ["--input_map_path", {from: input.user, attribute: reference_map_filepath}]
      - ["--output_folder",  "$OUTDIR"]
      - ["--gpu_id"        , "0,1"]
      - ["--num_components", "2"]
      - ["--batch_size"    , "8"]
      - ["--morph_radius"  , "3"]
      - ["--mask_diameter" , "95"]
      - ["--cutoff_prob"   , "0.3"]

  - name: reference_map_size
    script: size_estimation
    args:
      - ["--json"]
      - ["--volume", "$BASEDIR/reference_map_contour/prot_mask_final.mrc"]

  - name: negreg_size
    script: negative_estimation
    args:
      - ["--json"]
      - ["--output-dir", "$OUTDIR"]
      - ["--volume",     {from: input.user, attribute: reference_map_filepath}]
      - ["--mask",       "$BASEDIR/reference_map_contour/prot_mask_final.mrc"]

  - name: fresnel_boxsize
    script: boxsize_analysis
    args:
      - ["--json"]
      - ["fresnel"]
      - ["--particle_diameter", {from: analyses.reference_map_size, attribute: "radius"}]
      - ["--voltage",           {from: input.em_settings, attribute: EM_kV}]
      - ["--defocus",           "1"]
      - ["--resolution",        "2"]

css_config:
  inputs:
    EM_mics_apix: {from: input.em_settings, attribute: EM_mics_apix}

    SS_comm_lbin_angpix: {from: input.sample_settings, attribute: SS_comm_lbin_angpix}
    SS_comm_mbin_angpix: {from: input.sample_settings, attribute: SS_comm_mbin_angpix}

    GTF_lbin_abinit3d_pmd_increase_percentage: 1.2 # todo: get from file or compute
    mics_upper_bound: 4090 # todo: get from file or compute

    particle_contour_radius:        {from: "analyses.reference_map_size", attribute: "radius"}
    particle_contour_pixelsize:     {from: "analyses.reference_map_size", attribute: "voxel_size"}

    negative_density_region_radius:    {from: "analyses.negreg_size", attribute: "sphere_negative.radius"}
    negative_density_region_pixelsize: {from: "analyses.negreg_size", attribute: "sphere_negative.voxel_size"}

    fresnel_boxsize:                   {from: "analyses.fresnel_boxsize", attribute: "boxsize"}

  params_to_compute:
    # Common
    - SS_comm_class2d_pmd
    - SS_comm_optimal_pmd

    # 030_GTF_Create_Stack
    - GTF_lbin_extract_mics_box
    - GTF_lbin_extract_mics_0o95box
    - GTF_lbin_extract_parts_box
    - GTF_lbin_extract_parts_x_min
    - GTF_lbin_extract_parts_x_max
    - GTF_lbin_extract_parts_y_min
    - GTF_lbin_extract_parts_y_max

    # 050_GTF_AbInitReconst3D
    - GTF_lbin_abinit3d_pmd

    # 070_CSS_Init_Refine3D
    - CSS_mbin_reextract_mics_box
    - CSS_mbin_reextract_mics_0o95box
    - CSS_mbin_reextract_parts_box
    - CSS_mbin_reextract_parts_x_min
    - CSS_mbin_reextract_parts_x_max
    - CSS_mbin_reextract_parts_y_min
    - CSS_mbin_reextract_parts_y_max