environment:
  env:
    python_deepmasc    : /home/tmoriya/.pyenv/versions/anaconda3-2025.06-1/envs/DeepMASC/bin/python
    python_cryoem_tools: /home/tmoriya/.pyenv/versions/anaconda3-2025.06-1/envs/dev/bin/python

  toolbox:
    cryoread_contour: 
      env    : python_deepmasc
      script : /home/tmoriya/shared_for_all/apps/DeepMASC/contour.py

    size_estimation: 
      env    : python_cryoem_tools
      script : /home/tmoriya/shared_for_all/apps/rln_external/negative_region/size_estimation.py
    
    negative_estimation: 
      env    : python_cryoem_tools
      script : /home/tmoriya/shared_for_all/apps/rln_external/negative_region/negative_estimation.py

    boxsize_analysis:
      env    : python_cryoem_tools
      script : /home/tmoriya/shared_for_all/apps/rln_external/ctf_analysis/boxsize_analysis.py

analyses:
  - name: reference_map_contour
    script: cryoread_contour
    args:
      - ["--input_map_path", {from: input.user, attribute: reference_map}]
      - ["--output_folder",  "$OUTDIR"]
      - ["--gpu_id"        , "0,1"]
      - ["--num_components", "2"]
      - ["--batch_size"    , "8"]
      - ["--morph_radius"  , "3"]
      - ["--mask_diameter" , "95"]
      - ["--cutoff_prob"   , "0.3"]

  - name: reference_map_size
    script: size_estimation
    args:
      - ["--json"]
      - ["--volume", "$BASEDIR/reference_map_contour/prot_mask_final.mrc"]

  - name: negreg_size
    script: negative_estimation
    args:
      - ["--json"]
      - ["--output-dir", "$OUTDIR"]
      - ["--volume",     {from: input.user, attribute: reference_map}]
      - ["--mask",       "$BASEDIR/reference_map_contour/prot_mask_final.mrc"]

  - name: fresnel_boxsize
    script: boxsize_analysis
    args:
      - ["--json"]
      - ["fresnel"]
      - ["--particle_diameter", {from: analyses.reference_map_size, attribute: "radius"}]
      - ["--voltage",           {from: input.em_settings, attribute: EM_kV}]
      - ["--defocus",           "1"]
      - ["--resolution",        "2"]

css_inputs:
  particle_contour_radius:        {from: "analyses.reference_map_size", attribute: "radius"}
  particle_contour_pixelsize:     {from: "analyses.reference_map_size", attribute: "voxel_size"}

  negative_density_region_radius:    {from: "analyses.negreg_size", attribute: "sphere_negative.radius"}
  negative_density_region_pixelsize: {from: "analyses.negreg_size", attribute: "sphere_negative.voxel_size"}

  fresnel_boxsize:                   {from: "analyses.fresnel_boxsize",                attribute: "boxsize"}

input:
  input_map_filepath: "/home/tmoriya/shared_for_all/data/jair/EMPIAR10673_GPCR/PostProcess/job115/postprocess.mrc"
  em_settings_filepath:   "/home/tmoriya/shared_for_all/data/jair/autoparam/CS-Schemes/configs/common/config_em_settings.yml"