environment:
  env:
    python_deepmasc    : /home/tmoriya/.pyenv/versions/anaconda3-2025.06-1/envs/DeepMASC/bin/python
    python_cryoem_tools: /home/tmoriya/.pyenv/versions/anaconda3-2025.06-1/envs/dev/bin/python

  toolbox:
    cryoread_contour: 
      env    : python_deepmasc
      script : /home/tmoriya/shared_for_all/apps/DeepMASC/contour.py

    size_estimation: 
      env    : python_cryoem_tools
      script : /home/tmoriya/shared_for_all/apps/rln_external/negative_region/size_estimation.py
    
    negative_estimation: 
      env    : python_cryoem_tools
      script : /home/tmoriya/shared_for_all/apps/rln_external/negative_region/negative_estimation.py

    boxsize_analysis:
      env    : python_cryoem_tools
      script : /home/tmoriya/shared_for_all/apps/rln_external/ctf_analysis/boxsize_analysis.py