environment:
  env:
    python_deepmasc    : /home/tmoriya/.pyenv/versions/anaconda3-2025.06-1/envs/DeepMASC/bin/python
    python_cryoem_tools: /home/tmoriya/.pyenv/versions/anaconda3-2025.06-1/envs/dev/bin/python

  toolbox:
    cryoread_contour: 
      env    : python_deepmasc
      script : /home/tmoriya/shared_for_all/apps/DeepMASC/contour.py

    size_estimation: 
      env    : python_cryoem_tools
      script : /home/tmoriya/shared_for_all/apps/rln_external/negative_region/size_estimation.py
    
    negative_estimation: 
      env    : python_cryoem_tools
      script : /home/tmoriya/shared_for_all/apps/rln_external/negative_region/negative_estimation.py

    volume_alignment: 
      env    : python_cryoem_tools
      script : /home/tmoriya/shared_for_all/apps/rln_external/negative_region/volume_alignment.py

    boxsize_analysis:
      env    : python_cryoem_tools
      script : /home/tmoriya/shared_for_all/apps/rln_external/ctf_analysis/boxsize_analysis.py

analyses:
  - name: reference_map_contour
    script: cryoread_contour
    args:
      - ["--input_map_path", {from: input.user, attribute: reference_map_filepath}]
      - ["--output_folder",  "$OUTDIR"]
      - ["--gpu_id"        , "0,1"]
      - ["--num_components", "2"]
      - ["--batch_size"    , "8"]
      - ["--morph_radius"  , "3"]
      - ["--mask_diameter" , "95"]
      - ["--cutoff_prob"   , "0.3"]

  - name: reference_map_size
    script: size_estimation
    args:
      - ["--json"]
      - ["--volume", "$BASEDIR/reference_map_contour/prot_mask_final.mrc"]

  - name: negreg_size
    script: negative_estimation
    args:
      - ["--json"]
      - ["--output-dir", "$OUTDIR"]
      - ["--volume",     {from: input.user, attribute: reference_map_filepath}]
      - ["--mask",       "$BASEDIR/reference_map_contour/prot_mask_final.mrc"]

  - name: fresnel_boxsize
    script: boxsize_analysis
    args:
      - ["--json"]
      - ["fresnel"]
      - ["--particle_diameter", {from: analyses.reference_map_size, attribute: radius}]
      - ["--voltage",           {from: input.em_settings, attribute: EM_kV}]
      - ["--defocus",           {from: input.user, attribute: defocus, default: -1}]
      - ["--resolution",        {from: input.user, attribute: target_resolution, default: 3}]

  # add ctf here 
  - name: ctf_boxsize
    script: boxsize_analysis
    args:
      - ["--json"]
      - ["--output-dir", "$OUTDIR"]
      - ["opt"]
      - ["--pixel_size", {from: input.em_settings, attribute: EM_mics_apix}]
      - ["--voltage",    {from: input.em_settings, attribute: EM_kV}]
      - ["--defocus",    {from: input.user, attribute: defocus, default: 0}]
      - ["--cs",         {from: input.em_settings, attribute: EM_Cs}]
      - ["--save_plots"]

css_config:
  inputs:
    EM_mics_apix: {from: input.em_settings, attribute: EM_mics_apix}

    mics_upper_bound: {from: input.user, attribute: mics_size, default: 4090}

    ref3d_path : {from: input.user, attribute: reference_map_filepath}
    mask3d_path: "$BASEDIR/reference_map_contour/prot_mask_final.mrc"

    large_binning_factor : {from: input.user, attribute: large_binning_factor,  default: 4.00}
    medium_binning_factor: {from: input.user, attribute: medium_binning_factor, default: 1.24}

    padding_pixels    : {from: input.user, attribute: padding_pixels,     default: 0}
    padding_angstrom  : {from: input.user, attribute: padding_angstrom,   default: 0}
    padding_percentage: {from: input.user, attribute: padding_percentage, default: 0}

    reference_particle_size_pix:        {from: "analyses.reference_map_size", attribute: "diameter"}
    reference_particle_size_angpix:     {from: "analyses.reference_map_size", attribute: "voxel_size"}

    initial3d_particle_size_pix:        {from: "analyses.negreg_size", attribute: "sphere_negative.diameter"}
    initial3d_particle_size_angpix:     {from: "analyses.negreg_size", attribute: "sphere_negative.voxel_size"}

    ctflimit_boxsize_pix:               {from: "analyses.ctf_boxsize",    attribute: "boxsize"}
    ctflimit_boxsize_angpix:            {from: "analyses.ctf_boxsize",    attribute: "pixel_size"}

  params_to_compute:
    # Common
    - SS_comm_class2d_pmd
    - SS_comm_optimal_pmd
    - SS_comm_lbin_angpix
    - SS_comm_lbin_ref3d_path
    - SS_comm_lbin_ref3d_name
    - SS_comm_lbin_mask3d_path
    - SS_comm_lbin_mask3d_name
    - SS_comm_mbin_angpix

    # 030_GTF_Create_Stack
    - GTF_lbin_extract_mics_box
    - GTF_lbin_extract_mics_0o95box
    - GTF_lbin_extract_parts_box
    - GTF_lbin_extract_parts_x_min
    - GTF_lbin_extract_parts_x_max
    - GTF_lbin_extract_parts_y_min
    - GTF_lbin_extract_parts_y_max

    # 050_GTF_AbInitReconst3D
    - GTF_lbin_abinit3d_pmd

    # 070_CSS_Init_Refine3D
    - CSS_mbin_reextract_mics_box
    # - CSS_mbin_reextract_mics_0o95box
    # - CSS_mbin_reextract_parts_box
    # - CSS_mbin_reextract_parts_x_min
    # - CSS_mbin_reextract_parts_x_max
    # - CSS_mbin_reextract_parts_y_min
    # - CSS_mbin_reextract_parts_y_max

user_inputs:
  large_binning_factor : 4.00
  medium_binning_factor: 1.24

  # padding_pixels    : 0
  # padding_angstrom  : 0.0
  padding_percentage: 0.1

  defocus: -1.8

  target_resolution: 3

  mics_size: 3710