Settings:
  EM_movie_files: Movies/*.tiff
  EM_mtf_file: mtf_k2_200kV.star
  EM_mics_apix: 0.885
  EM_kV: 200
  EM_Cs: 1.4
  EM_first_frame_for_sum: 1
  EM_dose_per_frame: 1.277
  EM_motioncorr_bfactor: 150
  EM_motioncorr_patch_x: 5
  EM_motioncorr_patch_y: 5
  EM_ctffind_fit_res_min: 30
  EM_ctffind_fit_res_max: 5
